"""Add table history

Revision ID: 5fe07032db56
Revises: c34344b7c7b1
Create Date: 2021-05-05 22:39:41.231797

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5fe07032db56'
down_revision = 'c34344b7c7b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('histories', sa.Column('track_id', sa.Integer(), nullable=True))
    op.add_column('histories', sa.Column('title', sa.String(length=255), nullable=True))
    op.add_column('histories', sa.Column('preview', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('histories', 'preview')
    op.drop_column('histories', 'title')
    op.drop_column('histories', 'track_id')
    # ### end Alembic commands ###
