"""empty message

Revision ID: 9300f7da3be0
Revises: 
Create Date: 2021-05-05 13:33:56.700360

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9300f7da3be0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('histories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('musics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('preview', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('playlists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('reviews', sa.Column('title', sa.String(length=255), nullable=True))
    op.drop_column('reviews', 'track_title')
    op.add_column('users', sa.Column('profile_pic_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profile_pic_path')
    op.add_column('reviews', sa.Column('track_title', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('reviews', 'title')
    op.drop_table('playlists')
    op.drop_table('musics')
    op.drop_table('histories')
    op.drop_table('favorites')
    # ### end Alembic commands ###
