"""empty message

Revision ID: b011664d8826
Revises: 5f5ee95b559f
Create Date: 2021-05-05 20:25:36.163075

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b011664d8826'
down_revision = '5f5ee95b559f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('playlists', sa.Column('track_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('playlists', 'track_id')
    # ### end Alembic commands ###
