"""Add column user_id

Revision ID: df447b50cc98
Revises: 5fe07032db56
Create Date: 2021-05-05 23:07:30.823243

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df447b50cc98'
down_revision = '5fe07032db56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('favorites', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'favorites', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'favorites', type_='foreignkey')
    op.drop_column('favorites', 'user_id')
    # ### end Alembic commands ###
